### ISSUE TITLE
Cliant crash as requested be Sirsstud

### ISSUE THREAD

**Issue by miner-bob-1960** [MyM-ModpackTeam/hypovolemia#351]
[crash-2016-08-13_18.04.35-client.txt](https://github.com/MyM-ModpackTeam/hypovolemia/files/416666/crash-2016-08-13_18.04.35-client.txt)

**Comment by tyler489** [comment]
```---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 13/08/16 18:04
Description: Unexpected error

java.lang.NoClassDefFoundError: ivorius/ivtoolkit/random/WeightedSelector$WeightFunction
	at ivorius.reccomplex.blocks.TileEntityStructureGenerator.<init>(TileEntityStructureGenerator.java:22)
	at ivorius.reccomplex.blocks.BlockStructureGenerator.createTileEntity(BlockStructureGenerator.java:56)
	at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:850)
	at net.minecraft.world.ChunkCache.func_147438_o(ChunkCache.java:97)
	at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:304)
	at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:2256)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1556)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1337)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: ivorius.ivtoolkit.random.WeightedSelector$WeightFunction
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 17 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at ivorius.reccomplex.blocks.TileEntityStructureGenerator.<init>(TileEntityStructureGenerator.java:22)
	at ivorius.reccomplex.blocks.BlockStructureGenerator.createTileEntity(BlockStructureGenerator.java:56)
	at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:850)
	at net.minecraft.world.ChunkCache.func_147438_o(ChunkCache.java:97)
	at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:304)
	at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:2256)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1556)
```

**Comment by tyler489** [comment]
Simple fix Remove it from the loottable for chests

**Comment by chuggafan** [comment]
What mod is ivtoolkit? it appears to be from tile entitys containing an item + it's random number gene

**Comment by Messiah7** [comment]
ivtoolkit - lib\framework for Recurrent Complex

**Comment by chuggafan** [comment]
Can someone report this to him unless it's no longer being developed for this version of minecraft, thanks

**Comment by johnfg12** [comment]
created a issue with mod dev il close this since we cant fix it
